### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by odzb** [rubennorte/es6-object-assign#2]
This looks like the perfect object-assign polyfill, except for one flaw that can be fatal: please add a LICENSE file with the exact license text to the repo and to the NPM and bower packages. Simply stating that the license type is MIT is not enough, because the MIT license text requires the author's name and year to be filled in.

Would be great if you can fix this in timely manner so that we can include the module in the upcoming release of our software. Thanks in advance.

**Comment by rubennorte** [comment]
The LICENSE statement is already in the README.md file but I also included the LICENSE file in the latest version (1.0.2).
